# This is the configuration for pre-commit, a local framework for managing pre-commit hooks
#   Check out the docs at: https://pre-commit.com/

default_stages: [pre-commit]

# Exclude Matlab files
exclude: '.+\.m$'

repos:
-   repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.1
    hooks:
    -   id: nbqa-flake8
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-builtin-literals
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-toml
    -   id: detect-private-key
    -   id: end-of-file-fixer
        exclude: (\.min\.js$|\.svg$)
    -   id: trailing-whitespace
-   repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8  # See 'setup.cfg' for args
        args: [colorcet]
        files: colorcet/
-   repo: https://github.com/hoxbro/clean_notebook
    rev: v0.1.15a2
    hooks:
      - id: clean-notebook

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]
        additional_dependencies: [mypy-extensions==1.0.0, tokenize-rt==3.2.0]
        files: ^colorcet/.*\.py$
