name: tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
    - '*'

jobs:
  test_suite:
    name: Pytest on ${{ matrix.python-version }}, ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']
    timeout-minutes: 60
    defaults:
      run:
        shell: bash -l {0} 
    env:
      HV_REQUIREMENTS: "-o tests -o examples"
      PYCTDEV_SELF_CHANNEL: "pyviz"
      PYTHON_VERSION: ${{ matrix.python-version }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ENV_NAME: "colorcet"
      MPLBACKEND: "Agg"
      DISPLAY: ":99.0"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "100"
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          miniconda-version: "latest"
          channel-priority: strict
          channels: pyviz,conda-forge,nodefaults
      - name: Fetch
        run: git fetch --prune --tags -f
      - name: conda setup
        run: |
          conda --version
          conda install "pyctdev>=0.5"
          doit ecosystem_setup
          doit env_create --name=${{ env.ENV_NAME }} --python=${{ matrix.python-version }}
      - name: doit develop_install
        run: |
          eval "$(conda shell.bash hook)"
          conda activate ${{ env.ENV_NAME }}
          doit develop_install ${{ env.HV_REQUIREMENTS }}
      - name: doit env_capture
        run: |
          eval "$(conda shell.bash hook)"
          conda activate ${{ env.ENV_NAME }}
          doit env_capture
      - name: doit test_lint
        run: |
          eval "$(conda shell.bash hook)"
          conda activate ${{ env.ENV_NAME }}
          doit test_lint
      - name: doit test_unit
        run: |
          eval "$(conda shell.bash hook)"
          conda activate ${{ env.ENV_NAME }}
          doit test_unit
      - name: doit test_examples
        run: |
          eval "$(conda shell.bash hook)"
          conda activate ${{ env.ENV_NAME }}
          doit test_examples
      - name: doit test_unit_extra
        run: |
          eval "$(conda shell.bash hook)"
          conda activate ${{ env.ENV_NAME }}
          pip install pytest-mpl
          doit test_unit_extra
      - uses: codecov/codecov-action@v2

  test_suite_py27:
    name: Pytest on Python 2.7 only
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        python-version: [2.7]
    timeout-minutes: 60
    defaults:
      run:
        shell: bash -l {0} 
    env:
      HV_REQUIREMENTS: "tests"
      CHANS: "-c pyviz -c bokeh"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ENV_NAME: "colorcet"
      MPLBACKEND: "Agg"
      DISPLAY: ":99.0"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "100"
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          python-version: ${{ matrix.python-version }}
      - name: conda setup
        run: |
          conda config --set always_yes True
          conda --version
          conda install -c pyviz "pyctdev>=0.5"
          doit ecosystem_setup
          doit env_create --name=${{ env.ENV_NAME }} --python=${{ matrix.python-version }}
      - name: doit develop_install
        run: |
          eval "$(conda shell.bash hook)"
          conda activate ${{ env.ENV_NAME }}
          doit develop_install ${{ env.CHANS}} -o ${{ env.HV_REQUIREMENTS }}
      - name: doit env_capture
        run: |
          eval "$(conda shell.bash hook)"
          conda activate ${{ env.ENV_NAME }}
          doit env_capture
      - name: Handling backports on 'ubuntu-latest' and the decorator package
        if: matrix.os == 'ubuntu-latest'
        run: |
          eval "$(conda shell.bash hook)"
          conda activate ${{ env.ENV_NAME }}
          conda install ${{ env.CHANS}} backports.functools_lru_cache 'decorator=4.4.2'
      - name: doit env_capture again
        run: |
          eval "$(conda shell.bash hook)"
          conda activate ${{ env.ENV_NAME }}
          doit env_capture
      - name: doit test_unit
        if: matrix.os == 'ubuntu-latest'
        run: |
          eval "$(conda shell.bash hook)"
          conda activate ${{ env.ENV_NAME }}
          doit test_unit
      - name: doit test_unit
        if: matrix.os == 'macos-latest'
        run: |
          eval "$(conda shell.bash hook)"
          conda activate ${{ env.ENV_NAME }}
          pytest colorcet
